# Inspired by https://github.com/nginxinc/docker-nginx/blob/master/stable/buster/Dockerfile

# TODO Cleanup even more packages (lib stuff)
# TODO Do not enable useless deb-src?
# TODO Do we really need two ports exposed?
# TODO Use static build to simplify cleanup?
# TODO Find strategies to setup sites (at runtime? or build then extract? or volume?)
# TODO Document how to use it (I have to use it first) :)

---

- name: Containerized version of Nginx
  hosts: all

  tasks:
    - assert:
        that:
          - nginx_version is defined

    - name: Configure packages sources
      lineinfile:
        path: /etc/apt/sources.list
        regexp: deb-src (.*) {{ item }}$
        line: deb-src \1 {{ item }}
        backrefs: yes
        state: present
      loop:
        - '{{ ansible_distribution_release }} main restricted'
        - '{{ ansible_distribution_release }}-updates main restricted'
        - '{{ ansible_distribution_release }} universe'
        - '{{ ansible_distribution_release }}-updates universe'
        - '{{ ansible_distribution_release }} multiverse'
        - '{{ ansible_distribution_release }}-updates multiverse'
        - '{{ ansible_distribution_release }}-security main restricted'
        - '{{ ansible_distribution_release }}-security universe'
        - '{{ ansible_distribution_release }}-security multiverse'
      register: _apt_sources

    - name: Refresh package manager cache
      apt:
        update_cache: yes
      when: _apt_sources is change

    - import_role:
        name: nginx
      vars:
        nginx_role_action: setup

    - import_role:
        name: nginx
      vars:
        nginx_role_action: cleanup

    - meta: flush_handlers

    - name: Cleanup stuff (from 607 to 232 MB)
      raw: '{{ item }}'
      loop:
        - apt-get -y -qq remove --purge {{ packages|join(' ') }}
        - apt-get -y -qq autoremove
        - apt-get -y -qq autoclean
        - rm -rf {{ directores|join(' ') }}
      vars:
        directores:
          - /usr/include
          - /usr/lib/python3
          - /var/cache
        packages:
          - binutils
          - build-essential
          - cpp*
          - dpkg-dev
          - intltool-debian
          - less
          - m4
          - make
          - man-db
          - manpages*
          - patch
          - python3.*
          - quilt

  vars:
    do_become: no

    nginx_daemon_mode: container
    nginx_port: 8080
    nginx_port_ssl: 8443
    nginx_log_rotations: []  # Do not manage log rotation
    nginx_sites: {}          # Do not configure sites
    nginx_ufw_rules: []      # Do not install UFW

    nginx_version: release-1.15.6

    ansible_bender:

      ansible_extra_args: --diff
      cache_tasks: no
      layering: no
      squash: yes

      base_image: base:latest

      target_image:
        name: nginx
        ports:
          - '{{ nginx_port }}/tcp'
          - '{{ nginx_port_ssl }}/tcp'
        cmd: /usr/share/nginx/sbin/nginx -g daemon off;

      working_container:
        # volumes:
        #   - "{{ playbook_dir }}/../../roles:/home/david/.ansible/roles"
