# Inspired by https://github.com/nginxinc/docker-nginx/blob/master/stable/buster/Dockerfile

# TODO Cleanup even further stuff
# TODO Further reduce number of deb-src?
# TODO Do we really need two ports exposed?
# TODO Find strategies to setup sites (at runtime? or build then extract? or volume?)
# TODO Document how to use it (I have to use it first) :)

---

- name: Containerized version of Nginx
  hosts: all

  tasks:
    - assert:
        that:
          - nginx_version is defined

    - name: Configure packages sources
      lineinfile:
        path: /etc/apt/sources.list
        regexp: deb-src (.*) {{ item }}$
        line: deb-src \1 {{ item }}
        backrefs: yes
        state: present
      loop:
        - '{{ ansible_distribution_release }} main restricted'
        - '{{ ansible_distribution_release }}-updates main restricted'
        - '{{ ansible_distribution_release }} universe'
        - '{{ ansible_distribution_release }}-updates universe'
        - '{{ ansible_distribution_release }} multiverse'
        - '{{ ansible_distribution_release }}-updates multiverse'
        - '{{ ansible_distribution_release }}-security main restricted'
        - '{{ ansible_distribution_release }}-security universe'
        - '{{ ansible_distribution_release }}-security multiverse'
      register: _apt_sources

    - name: Refresh package manager cache
      apt:
        update_cache: yes
      when: _apt_sources is change

    - import_role:
        name: nginx
      vars:
        nginx_role_action: setup

    - import_role:
        name: nginx
      vars:
        nginx_role_action: cleanup

    - name: Cleanup stuff
      raw: '{{ item }}'
      loop:
        - apt-get -y -qq autoremove
        - apt-get -y -qq autoclean
        - apt-get -y -qq remove --purge python3 python3-apt python3-pip python3-setuptools
      no_log: yes

  vars:
    do_become: no

    nginx_daemon_mode: container
    nginx_port: 8080
    nginx_port_ssl: 8443
    nginx_log_rotations: []  # Do not manage log rotation
    nginx_sites: {}          # Do not configure sites
    nginx_ufw_rules: []      # Do not install UFW

    nginx_version: release-1.15.6

    ansible_bender:

      ansible_extra_args: --diff
      cache_tasks: no
      layering: no

      base_image: base:latest

      target_image:
        name: nginx
        ports:
          - '{{ nginx_port }}/tcp'
          - '{{ nginx_port_ssl }}/tcp'
        cmd: /usr/share/nginx/sbin/nginx -g daemon off;

      working_container:
        # volumes:
        #   - "{{ playbook_dir }}/../../roles:/home/david/.ansible/roles"
