# Inspired by https://github.com/nginxinc/docker-nginx/blob/master/stable/buster/Dockerfile
---

- name: Containerized version of Nginx
  hosts: all

  tasks:
    - name: Configure packages sources
      lineinfile:
        path: /etc/apt/sources.list
        regexp: deb-src (.*) {{ item }}$
        line: deb-src \1 {{ item }}
        backrefs: yes
        state: present
      loop:
        - '{{ ansible_distribution_release }} main restricted'
        - '{{ ansible_distribution_release }}-updates main restricted'
        - '{{ ansible_distribution_release }} universe'
        - '{{ ansible_distribution_release }}-updates universe'
        - '{{ ansible_distribution_release }} multiverse'
        - '{{ ansible_distribution_release }}-updates multiverse'
        - '{{ ansible_distribution_release }}-security main restricted'
        - '{{ ansible_distribution_release }}-security universe'
        - '{{ ansible_distribution_release }}-security multiverse'
      register: _apt_sources

    - name: Refresh package manager cache
      apt:
        update_cache: yes
      when: _apt_sources is change

    - include_role:
        name: nginx
      loop:
        - setup
        - cleanup
      vars:
        nginx_role_action: '{{ item }}'

    - name: Cleanup stuff
      raw: >
        apt-get -y -qq remove --purge python3 python3-apt python3-pip python3-setuptools &&
        apt-get -y -qq autoremove &&
        apt-get -y -qq autoclean

  vars:
    do_become: no

    nginx_daemon_mode: container
    nginx_port: 8080
    nginx_port_ssl: 8443
    nginx_log_rotations: []  # Do not manage log rotation
    nginx_sites: {}          # Do not configure sites
    nginx_ufw_rules: []      # Do not install UFW

    # FIXME as a parameter
    nginx_version: release-1.15.6

    ansible_bender:

      ansible_extra_args: --diff
      cache_tasks: no
      layering: no

      base_image: base:latest

      target_image:
        name: nginx
        ports:
          - '{{ nginx_port }}/tcp'
          - '{{ nginx_port_ssl }}/tcp'
        cmd: /usr/share/nginx/sbin/nginx -g daemon off;

      working_container:
        # volumes:
        #   - "{{ playbook_dir }}/../../roles:/home/david/.ansible/roles"
